# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

orbs: 
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.1.2

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer update
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run:
          name: "Create Environment file and generate app key"
          command: |
            mv .env.testing .env
            php artisan key:generate

      - run:
          name: "Create database and run migration"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing

      - run:
          name: "Generate Passport encryption keys"
          command: php artisan passport:install

      # run tests with phpunit
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit

      # send discord webhook
      - discord/status:
          fail_only: true
          failure_message: "${CIRCLE_USERNAME}'s build in ${CIRCLE_BRANCH}: ${CIRCLE_JOB} failed."
          webhook: "${discord_webhook}"
  deploy:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
    - checkout
    - run: npm install
    - run:
        name: Deploy main branch on remote ftp server
        command: |
          sudo apt-get update
          sudo apt-get -qq install git-ftp
          echo "Deploying project to ftp server..."
          git ftp push --user "${username}" --passwd "${password}" ${ftp_location}
    - run:
        name: Restart Laravel project
        command: |
          sudo apt-get -qq install sshpass
          echo "Restarting artisan"
          sshpass -p "${password}" ssh ${username}@${ssh_server} -p 7685
          cd ${ssh_directory}
          composer update -W
          php artisan optimize:clear
          php artisan serve

    # send discord webhook
    - discord/status:
        fail_only: false
        failure_message: "${CIRCLE_USERNAME}'s build: ${CIRCLE_JOB} failed."
        webhook: "${discord_webhook}"
        success_message: "${CIRCLE_USERNAME} deployed ${CIRCLE_BRANCH} to ${ftp_location} ."

workflows:
  version: 2
  build-branch-deploy-if-main:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build